# Generated by Django 2.1.4 on 2019-01-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
