# Generated by Django 2.1.4 on 2019-01-05 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190105_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSerializer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Account')),
            ],
            bases=('user.account',),
        ),
    ]
